server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Это самое главное для React-роутинга: если файла нет, отдавать index.html
        try_files $uri $uri/ /index.html;
    }
}
