version: '3.8'

services:
  ocr_engine:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://ocr_user:ocr_password@db:5432/ocr_db
      - LLM_PROVIDER=gigachat
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - ocr_net

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=ocr_user
      - POSTGRES_PASSWORD=ocr_password
      - POSTGRES_DB=ocr_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ocr_net

  frontend:
    image: dockerhub.timeweb.cloud/library/node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - ocr_engine
    networks:
      - ocr_net

networks:
  ocr_net:
    driver: bridge
    ipam:
      config:
        - subnet: 12.10.1.0/24

volumes:
  postgres_data:
