version: '3.8'

services:
  orchestrator:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      # Папка с конфигурациями для каждого отдельного сайта/домена
      - ./conf.d:/etc/nginx/conf.d:ro
    extra_hosts:
      # Позволяет Nginx стучаться на порты основного сервера (localhost)
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 12.10.3.0/24
