"""Add user auth system

Revision ID: a9ae8477d3b0
Revises: 
Create Date: 2026-03-26 16:55:59.322902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ae8477d3b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'processing_jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processing_jobs', type_='foreignkey')
    op.drop_column('processing_jobs', 'user_id')
    # ### end Alembic commands ###
